import React from 'react';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

const NeighborhoodContent = ({ content, faq }) => {
  if (!content) return null;

  return (
    <div className="bg-white rounded-2xl p-6 md:p-10 shadow-sm border border-gray-100">
      {/* Render HTML Content safely since it's generated by our trusted internal generator */}
      <div 
        className="prose max-w-none prose-headings:text-[#1a3a52] prose-p:text-gray-700 prose-a:text-blue-600 mb-12"
        dangerouslySetInnerHTML={{ __html: content }} 
      />

      {/* FAQ Section */}
      {faq && faq.length > 0 && (
        <div className="mt-12 border-t border-gray-100 pt-10">
          <h2 className="text-2xl font-bold text-[#1a3a52] mb-6">Perguntas Frequentes sobre {faq[0].question.split('morar em ')[1]?.replace('?', '') || 'o Bairro'}</h2>
          <Accordion type="single" collapsible className="w-full">
            {faq.map((item, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger className="text-left font-semibold text-gray-800 hover:text-[#0d5a7a]">
                  {item.question}
                </AccordionTrigger>
                <AccordionContent className="text-gray-600 leading-relaxed">
                  {item.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      )}
    </div>
  );
};

export default NeighborhoodContent;